version: "3"
services:
  api:
    env_file:
      - .env
    build: ./
    container_name: nodejs
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - mongo-express
    ports:
      - ${PORT_APP}:${PORT_APP}
    networks:
      - app-network
  mongo:
    env_file:
      - .env
    container_name: mongo
    volumes:  
      - dbdata:/data/db   
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - app-network
    ports:
      - 27017:27017
    networks:
      - app-network
  mongo-express:
    env_file:
      - .env
    container_name: mongo_express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
    networks:
      - app-network
volumes:
    dbdata:
networks:
  app-network:
    driver: bridge